// ==========================================================================
// Acadex — "Acadex Sunum" AI Asistanı panel actions (per-slide content AI)
//
// The AI Asistanı sidebar inside acadex-sunum.html (Bu Slaydı Zenginleştir,
// Konuya Göre Yeniden Yaz, Bu Slaytı Yeniden Üret, Soru Ekle, Ton Değiştir,
// Konuşmacı Notu Üret, AI Slayt Oluştur) used to be powered by local
// hardcoded template strings — generic productivity clichés ("üretim
// ritmi", "kontrol listesi" etc.) that had nothing to do with the actual
// presentation topic. This function replaces those with real, topic-
// grounded content generated by Groq, one action at a time.
//
// Stateless: nothing is written to Supabase — the caller applies the
// returned text directly onto the Fabric.js canvas / notes field.
//
// Deploy: `supabase functions deploy generate-slide-content`, using the
// same GROQ_API_KEY secret already used by generate-exam / grade-exam /
// acadia-assistant / generate-presentation.
// ==========================================================================
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

const ALLOWED_ACTIONS = ['enrich', 'rewrite', 'regenerate', 'question', 'tone', 'notes', 'notes_all', 'new_slide']

const TONE_HINTS: Record<string, string> = {
  academic: 'Akademik bir dille yazın; kavramları net tanımlayın, terminolojiye özen gösterin — ama gerçek, spesifik bilgiden asla sapmayın.',
  corporate: 'Kurumsal ve karar odaklı bir dille yazın; net, aksiyona dönük ifadeler kullanın — ama gerçek, spesifik bilgiden asla sapmayın.',
  creative: 'Daha canlı, akıcı bir dil kullanın; dinleyiciyi ilgiyle bağlayın — ama gerçek bilgiden asla sapmayın, uydurmayın.',
  summary: 'Kısa, net, madde işaretine uygun cümleler kurun; gereksiz süslemeden kaçının — ama içerik yine spesifik ve gerçek olsun.'
}

function isTokenSizeError(status: number, body: any): boolean {
  return (status === 400 || status === 429 || status === 413) &&
    (body?.error?.code === 'rate_limit_exceeded' || /token/i.test(String(body?.error?.message || '')))
}

const GROUNDING_RULE = `KRİTİK KURAL: Bütün çıktı, verilen KONU hakkında gerçek, spesifik, doğru bilgi içermelidir (gerçek tarihler, isimler, sayılar, nedenler, mekanizmalar, örnekler — konuya göre neyse). "Erken netlik zaman kazandırır", "düzenli üretim ritmi", "kontrol listesi kullanın" gibi konudan bağımsız, jenerik prodüktivite klişeleri KESİNLİKLE YASAK — bunlar konuşulan KONU ile ilgisiz olduğu için kabul edilemez. Metin, konunun kendisi hakkında olmalı, konu hakkında konuşmak hakkında değil.`

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (req.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), {
        status: 405,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    const body = await req.json()
    const action = body?.action
    if (!ALLOWED_ACTIONS.includes(action)) {
      return new Response(JSON.stringify({ error: 'Invalid or missing "action" parameter' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    const topic = String(body?.topic || '').trim().slice(0, 200) || 'Genel konu'
    const slideTitle = String(body?.slideTitle || '').trim().slice(0, 150)
    const currentText = String(body?.currentText || '').trim().slice(0, 2000)
    const tone = TONE_HINTS[body?.tone] ? body.tone : 'academic'
    const language = (body?.language === 'en') ? 'en' : 'tr'
    const langLine = language === 'tr' ? 'Türkçe' : 'English'

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Missing Authorization header' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    })
    const { data: { user }, error: userError } = await userClient.auth.getUser()
    if (userError || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized user token' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    const groqApiKey = Deno.env.get('GROQ_API_KEY')
    if (!groqApiKey) {
      return new Response(JSON.stringify({ error: 'Groq API key not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    // ---- Build action-specific prompt + expected JSON shape --------------
    let systemPrompt = ''
    let userPrompt = ''

    if (action === 'enrich') {
      systemPrompt = `
Sen bir sunum içerik editörüsün. KONU: "${topic}". Mevcut slayt başlığı: "${slideTitle || topic}".
Görevin: aşağıda verilen mevcut slayt metnini, aynı konuyu ele alarak daha DERİN ve daha ZENGİN içerikli hale getirmek — daha fazla gerçek detay, örnek, sayı, neden-sonuç ekleyerek.
${GROUNDING_RULE}
Çıktı: 4-6 madde işaretli (•) satır, her biri gerçek ve spesifik bilgi içersin, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"content": "• ...\\n• ...\\n..."}`.trim()
      userPrompt = `Mevcut metin:\n${currentText || '(boş, sıfırdan üret)'}`
    } else if (action === 'rewrite') {
      systemPrompt = `
Sen bir sunum içerik editörüsün. KONU: "${topic}". Mevcut slayt başlığı: "${slideTitle || topic}".
Görevin: aşağıdaki metni, aynı konuya odaklanarak SIFIRDAN, farklı bir açıdan yeniden yazmak.
${GROUNDING_RULE}
Çıktı: 4-6 madde işaretli (•) satır, her biri gerçek ve spesifik bilgi içersin, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"content": "• ...\\n• ...\\n..."}`.trim()
      userPrompt = `Mevcut metin (referans için, birebir tekrarlama):\n${currentText || '(boş)'}`
    } else if (action === 'tone') {
      systemPrompt = `
Sen bir sunum içerik editörüsün. KONU: "${topic}". Mevcut slayt başlığı: "${slideTitle || topic}".
Görevin: aşağıdaki metni aynı gerçek bilgiyi koruyarak farklı bir TON'da yeniden yazmak.
Ton talimatı: ${TONE_HINTS[tone]}
${GROUNDING_RULE}
Çıktı: 3-5 madde işaretli (•) satır, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"content": "• ...\\n• ...\\n..."}`.trim()
      userPrompt = `Mevcut metin:\n${currentText || topic}`
    } else if (action === 'regenerate') {
      systemPrompt = `
Sen bir sunum yazarısın. KONU: "${topic}". Bu slaytın mevcut başlığı: "${slideTitle || topic}" (referans amaçlı, birebir kopyalama).
Görevin: bu slaytı, konuyla ilgili gerçek ve spesifik bir alt-başlıkla SIFIRDAN yeniden üretmek.
${GROUNDING_RULE}
Çıktı: kısa, spesifik bir başlık + 4-6 madde işaretli (•) satırlık gövde metni, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"title": "string", "content": "• ...\\n• ...\\n..."}`.trim()
      userPrompt = `Mevcut gövde metni (referans için):\n${currentText || '(boş)'}`
    } else if (action === 'question') {
      systemPrompt = `
Sen bir sunum tasarımcısısın. KONU: "${topic}". Slayt başlığı: "${slideTitle || topic}".
Görevin: bu slaydın içeriğine dayanan, dinleyiciyi düşündürecek TEK bir spesifik tartışma sorusu yazmak — konuyla ilgili gerçek bir detaya değinen, jenerik olmayan bir soru.
${GROUNDING_RULE}
${langLine} dilinde yaz.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"question": "string"}`.trim()
      userPrompt = `Slayt içeriği:\n${currentText || topic}`
    } else if (action === 'notes') {
      systemPrompt = `
Sen bir sunum koçusun. KONU: "${topic}". Slayt başlığı: "${slideTitle || topic}".
Görevin: bu slayt için gerçek, konuya özgü konuşmacı notları (speaker notes) yazmak — sunucunun sözlü olarak söyleyeceği, slaytın içeriğine dayanan somut bilgi ve bağlam.
${GROUNDING_RULE}
Çıktı: 3-5 cümlelik akıcı bir paragraf, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"notes": "string"}`.trim()
      userPrompt = `Slayt içeriği:\n${currentText || topic}`
    } else if (action === 'notes_all') {
      const allSlides = Array.isArray(body?.allSlides) ? body.allSlides.slice(0, 20) : []
      systemPrompt = `
Sen bir sunum koçusun. KONU: "${topic}". Aşağıda bir sunumun tüm slaytlarının başlık ve içerikleri sırasıyla verilmiştir.
Görevin: HER slayt için ayrı, gerçek ve konuya özgü konuşmacı notları (speaker notes) yazmak.
${GROUNDING_RULE}
Her not 2-4 cümle olsun, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma, dizinin uzunluğu verilen slayt sayısıyla AYNI olmalı:
{"notesList": ["slayt 1 notu", "slayt 2 notu", "..."]}`.trim()
      userPrompt = allSlides.map((s: any, i: number) =>
        `Slayt ${i + 1} — Başlık: ${String(s?.title || '').slice(0, 120)}\nİçerik: ${String(s?.content || '').slice(0, 400)}`
      ).join('\n\n')
    } else if (action === 'new_slide') {
      const existingTitles = Array.isArray(body?.existingTitles) ? body.existingTitles.slice(0, 30) : []
      systemPrompt = `
Sen bir sunum yazarısın. KONU: "${topic}".
Görevin: bu sunuma eklenecek YENİ, gerçek ve spesifik içerikli TEK bir slayt üretmek — konunun henüz ele alınmamış bir yönüne odaklanarak (aşağıdaki mevcut başlıklarla anlamlı biçimde çakışmasın).
${GROUNDING_RULE}
Çıktı: kısa, spesifik bir başlık + 4-6 madde işaretli (•) satırlık gövde metni, ${langLine} dilinde.
SADECE şu JSON formatında cevap ver, başka hiçbir şey yazma: {"title": "string", "content": "• ...\\n• ...\\n..."}`.trim()
      userPrompt = existingTitles.length ? `Mevcut slayt başlıkları (tekrar etme):\n${existingTitles.join('\n')}` : 'Henüz başka slayt yok.'
    }

    const callGroq = async (bulletsHint: string) => {
      const resp = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${groqApiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          temperature: 0.8,
          response_format: { type: "json_object" },
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `${userPrompt}\n\nVaryasyon tohumu: ${Date.now()}` }
          ]
        })
      })
      const data = await resp.json()
      return { resp, data }
    }

    let { resp: groqResponse, data: groqData } = await callGroq('4-6')
    if (!groqResponse.ok && isTokenSizeError(groqResponse.status, groqData)) {
      console.warn('generate-slide-content: token-size error, retrying shorter.')
      // Trim currentText further and retry once
      userPrompt = userPrompt.slice(0, 600)
      ;({ resp: groqResponse, data: groqData } = await callGroq('2-3'))
    }

    if (!groqResponse.ok) {
      console.error("generate-slide-content Groq call failed: ", groqData)
      return new Response(JSON.stringify({ error: 'AI generation service failed. Please try again in a moment.' }), {
        status: 502,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    const rawContent = groqData.choices?.[0]?.message?.content ?? ""
    const cleaned = rawContent.replace(/```json\s*|```/g, "").trim()

    let parsed: any
    try {
      parsed = JSON.parse(cleaned)
    } catch (e) {
      console.error("Failed to parse Groq response as JSON. Content: ", rawContent, e)
      return new Response(JSON.stringify({ error: 'AI returned invalid formatting. Please try again.' }), {
        status: 502,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    // Sanitize / cap fields depending on action
    const out: Record<string, unknown> = {}
    if (typeof parsed?.content === 'string') out.content = parsed.content.trim().slice(0, 2000)
    if (typeof parsed?.title === 'string') out.title = parsed.title.trim().slice(0, 120)
    if (typeof parsed?.question === 'string') out.question = parsed.question.trim().slice(0, 300)
    if (typeof parsed?.notes === 'string') out.notes = parsed.notes.trim().slice(0, 800)
    if (Array.isArray(parsed?.notesList)) out.notesList = parsed.notesList.map((n: any) => String(n || '').trim().slice(0, 800))

    if (Object.keys(out).length === 0) {
      console.error("AI response missing expected fields for action:", action, parsed)
      return new Response(JSON.stringify({ error: 'AI response was empty or malformed.' }), {
        status: 502,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    return new Response(JSON.stringify(out), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })

  } catch (err) {
    console.error("generate-slide-content exception: ", err)
    return new Response(JSON.stringify({ error: 'Internal server error occurred' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})
